export type BlogCategory = "Buying" | "VA loans" | "Self-employed" | "Market strategy" | "Homeownership";

export type BlogPost = {
  title: string;
  description: string;
  date: string;
  category: BlogCategory;
  url: string;
};

// Complete fallback archive. The live endpoint refreshes this list in the browser.
export const blogPosts: BlogPost[] = [
  {
    title: "Orlando FHA 203k Renovation Loan Basics for Buyers",
    description: "Orlando FHA 203k renovation loan basics for Florida buyers: how financing repairs works, contractors, escrow, timelines, appraisal rules, and approval risks.",
    date: "July 8, 2026",
    category: "Homeownership",
    url: "https://drmortgageusa.com/blog/orlando-fha-203k-renovation-loan-basics",
  },
  {
    title: "Florida Bank Statement Mortgage Loans for Self-Employed Borrowers",
    description: "Florida bank statement mortgage loans for self-employed Orlando buyers: how they work, documents needed, risks, reserves, and questions to ask.",
    date: "July 2, 2026",
    category: "Self-employed",
    url: "https://drmortgageusa.com/blog/florida-bank-statement-mortgage-loans-self-employed",
  },
  {
    title: "Florida Mortgage Gift Funds Rules for Homebuyers",
    description: "Florida mortgage gift funds rules for Orlando buyers in 2026: who can give money, gift letters, bank statements, FHA, VA, and conventional rules.",
    date: "June 29, 2026",
    category: "VA loans",
    url: "https://drmortgageusa.com/blog/florida-mortgage-gift-funds-rules-2026",
  },
  {
    title: "Florida Self-Employed Borrower Documentation Checklist",
    description: "Florida self-employed mortgage checklist for Orlando buyers in 2026: tax returns, bank statements, P&L, K-1s, income history, and lender documentation tips.",
    date: "June 26, 2026",
    category: "Self-employed",
    url: "https://drmortgageusa.com/blog/florida-self-employed-borrower-documentation-checklist",
  },
  {
    title: "Rate Buydown vs Price Reduction for Florida Buyers",
    description: "Compare rate buydown vs price reduction for Florida buyers in 2026, including monthly payment, cash to close, seller credits, and Orlando mortgage strategy.",
    date: "June 23, 2026",
    category: "Market strategy",
    url: "https://drmortgageusa.com/blog/rate-buydown-vs-price-reduction-florida-buyers",
  },
  {
    title: "Condo Financing Red Flags in Florida",
    description: "Florida condo financing red flags for 2026, including warrantable rules, HOA issues, insurance, reserves, litigation, and Orlando buyer checks before offers.",
    date: "June 20, 2026",
    category: "Buying",
    url: "https://drmortgageusa.com/blog/condo-financing-red-flags-florida-2026",
  },
  {
    title: "VA Residual Income Explained for Florida Veterans",
    description: "VA residual income explained for Florida veterans buying in Orlando, including family size, region rules, debts, taxes, childcare, and what lenders review.",
    date: "June 17, 2026",
    category: "VA loans",
    url: "https://drmortgageusa.com/blog/va-residual-income-florida-veterans-2026",
  },
  {
    title: "Orlando Move-Up Buyer Strategy: Keep Cash Without Overbuying",
    description: "Orlando move-up buyer strategy for Florida homeowners who need cash reserves, seller credits, payment control, and a mortgage plan before buying.",
    date: "June 14, 2026",
    category: "Buying",
    url: "https://drmortgageusa.com/blog/orlando-move-up-buyer-strategy-keeping-cash",
  },
  {
    title: "Florida Escrow Shortage After Buying a Home: Why Payments Jump",
    description: "Florida escrow shortage guide for homeowners. Learn why mortgage payments jump after buying, how taxes and insurance affect escrow, and what to check.",
    date: "June 11, 2026",
    category: "Homeownership",
    url: "https://drmortgageusa.com/blog/florida-escrow-shortage-payment-jump",
  },
  {
    title: "VA Appraisal Repairs in Florida: What Veterans Should Know Before Closing",
    description: "Florida veterans using VA loans should understand VA appraisal repairs, minimum property requirements, seller negotiations, insurance issues, and closing delays.",
    date: "June 8, 2026",
    category: "VA loans",
    url: "https://drmortgageusa.com/blog/va-appraisal-repairs-florida-2026",
  },
  {
    title: "New Construction Builder Incentives in Orlando: What Buyers Should Check First",
    description: "Orlando new construction buyers should compare builder incentives, preferred lender credits, rate buydowns, closing costs, and total mortgage payment in 2026.",
    date: "June 5, 2026",
    category: "Market strategy",
    url: "https://drmortgageusa.com/blog/new-construction-builder-incentives-orlando-2026",
  },
  {
    title: "How Florida Homeowners Insurance Can Affect Your Mortgage Approval",
    description: "Florida homeowners insurance can affect mortgage approval, monthly payment, debt-to-income ratio, cash to close, and Orlando buyer affordability in 2026.",
    date: "June 2, 2026",
    category: "Homeownership",
    url: "https://drmortgageusa.com/blog/florida-homeowners-insurance-mortgage-approval-2026",
  },
  {
    title: "What Florida Buyers Should Know Before Waiving Inspections or Repairs",
    description: "Florida buyers should understand inspection waivers, repair limits, insurance issues, appraisal risk, and Orlando contract strategy before making an offer.",
    date: "May 30, 2026",
    category: "Buying",
    url: "https://drmortgageusa.com/blog/florida-buyers-waiving-inspections-repairs-2026",
  },
  {
    title: "How to Compare Mortgage Quotes: APR, Points, Lender Credits, and Fees",
    description: "Learn how to compare mortgage quotes in Florida, including APR, points, lender credits, fees, closing costs, and Orlando buyer mistakes to avoid in 2026.",
    date: "May 27, 2026",
    category: "Buying",
    url: "https://drmortgageusa.com/blog/how-to-compare-mortgage-quotes-apr-points-lender-credits-fees",
  },
  {
    title: "VA Loan Seller Concessions in Florida: What Veterans Can and Cannot Use Them For",
    description: "VA loan seller concessions in Florida explained for veterans. Learn what sellers can pay, what credits cover, and how Orlando buyers use them in 2026.",
    date: "May 24, 2026",
    category: "VA loans",
    url: "https://drmortgageusa.com/blog/va-loan-seller-concessions-florida",
  },
  {
    title: "Why Your Pre-Approval Amount Is Not Your Real Homebuying Budget",
    description: "Why your mortgage pre-approval amount is not your real homebuying budget in Orlando, Florida. Learn payment comfort, taxes, insurance, DTI, and cash to close.",
    date: "May 22, 2026",
    category: "Buying",
    url: "https://drmortgageusa.com/blog/why-preapproval-amount-not-real-homebuying-budget",
  },
  {
    title: "VA Loan Occupancy Requirements in Florida: 2026 Guide",
    description: "VA loan occupancy requirements in Florida for 2026. Learn the 60-day rule, spouse occupancy, PCS exceptions, and Orlando buyer mistakes to avoid today.",
    date: "May 9, 2026",
    category: "VA loans",
    url: "https://drmortgageusa.com/blog/va-loan-occupancy-requirements-florida-2026",
  },
  {
    title: "VA Termite Inspection Requirements in Florida: 2026 Guide",
    description: "VA termite inspection requirements in Florida for 2026. Learn when wood-destroying insect reports are required and how Orlando VA buyers avoid delays.",
    date: "May 6, 2026",
    category: "VA loans",
    url: "https://drmortgageusa.com/blog/va-termite-inspection-requirements-florida-2026",
  },
  {
    title: "VA Minimum Property Requirements in Florida: 2026 Guide",
    description: "VA minimum property requirements Florida guide for 2026. Learn what VA appraisers check, common repair issues, and how Orlando buyers can avoid delays.",
    date: "May 3, 2026",
    category: "VA loans",
    url: "https://drmortgageusa.com/blog/va-minimum-property-requirements-florida-2026",
  },
  {
    title: "Credit Repair Strategy for Buying a Home in Florida",
    description: "Credit repair strategy for buying a home in Florida. Learn what hurts approval, how to raise scores, and what Orlando buyers should fix first in 2026.",
    date: "April 24, 2026",
    category: "Buying",
    url: "https://drmortgageusa.com/blog/credit-repair-strategy-buying-home-florida",
  },
  {
    title: "Investment Property Loans in Florida: 2026 Guide",
    description: "Investment property loans in Florida for 2026. Learn down payment requirements, rates, reserves, and what Orlando real estate investors need to qualify.",
    date: "April 22, 2026",
    category: "Market strategy",
    url: "https://drmortgageusa.com/blog/investment-property-loans-florida-2026",
  },
  {
    title: "Florida Homestead Exemption Guide for New Homeowners",
    description: "Florida homestead exemption guide for new homeowners. Learn how it lowers property taxes, when to file, and what Orlando buyers need to know in 2026.",
    date: "April 17, 2026",
    category: "Homeownership",
    url: "https://drmortgageusa.com/blog/florida-homestead-exemption-guide-new-homeowners",
  },
  {
    title: "How Property Taxes Work in Florida for New Homebuyers",
    description: "Learn how property taxes work in Florida for new homebuyers, including reassessment, homestead impact, escrows, and what Orlando buyers should budget for in 2026.",
    date: "April 14, 2026",
    category: "Homeownership",
    url: "https://drmortgageusa.com/blog/how-property-taxes-work-florida-new-homebuyers",
  },
  {
    title: "HOA and Condo Financing in Florida: Warrantable vs Non-Warrantable",
    description: "Buying a condo in Florida? Learn how warrantable vs non-warrantable condo financing works, what Orlando buyers should watch, and how HOA rules can impact approval.",
    date: "April 11, 2026",
    category: "Buying",
    url: "https://drmortgageusa.com/blog/hoa-condo-financing-florida-warrantable-vs-non-warrantable",
  },
  {
    title: "Refinancing Out of FHA to Conventional in Florida",
    description: "Thinking about refinancing out of FHA to conventional in Florida? Learn when it makes sense, how to remove mortgage insurance, and what Orlando homeowners need to qualify.",
    date: "April 7, 2026",
    category: "Market strategy",
    url: "https://drmortgageusa.com/blog/refinancing-out-of-fha-to-conventional-florida",
  },
  {
    title: "Debt-to-Income Ratio Explained for Florida Homebuyers",
    description: "Learn how debt-to-income ratio affects your mortgage approval in Florida. DTI limits for VA, FHA, and conventional loans, plus strategies to lower yours in Orlando.",
    date: "March 30, 2026",
    category: "VA loans",
    url: "https://drmortgageusa.com/blog/debt-to-income-ratio-florida-homebuyers",
  },
  {
    title: "VA Funding Fee Guide 2026: Who Pays, Exemptions, and How It Works",
    description: "Complete VA funding fee guide for 2026. Learn current rates, who qualifies for exemptions, how to finance it, and what it means for Florida veterans buying a home.",
    date: "March 24, 2026",
    category: "VA loans",
    url: "https://drmortgageusa.com/blog/va-funding-fee-guide-2026",
  },
  {
    title: "Closing Costs in Florida Explained: What You'll Actually Pay in 2026",
    description: "Complete breakdown of closing costs in Florida for 2026. Learn what buyers and sellers pay, typical amounts in Orlando, and how to reduce your out-of-pocket costs.",
    date: "March 21, 2026",
    category: "Buying",
    url: "https://drmortgageusa.com/blog/closing-costs-florida-explained-2026",
  },
  {
    title: "Mortgage Preapproval vs Prequalification in Florida: What's the Difference?",
    description: "Preapproval vs prequalification in Florida: learn the real difference, which one sellers and realtors require, and how to get a strong preapproval in Orlando.",
    date: "March 18, 2026",
    category: "Buying",
    url: "https://drmortgageusa.com/blog/mortgage-preapproval-vs-prequalification-florida",
  },
  {
    title: "How Much House Can You Afford in Orlando? 2026 Guide",
    description: "How much house can you afford in Orlando? Calculate your home buying budget using income, debt, and down payment. Real affordability guidance for 2026 buyers.",
    date: "March 17, 2026",
    category: "Buying",
    url: "https://drmortgageusa.com/blog/how-much-house-afford-orlando-2026",
  },
  {
    title: "What Happens at a Mortgage Closing in Florida: Step-by-Step Guide 2026",
    description: "Complete guide to Florida mortgage closings in 2026. Learn what documents you",
    date: "March 15, 2026",
    category: "Buying",
    url: "https://drmortgageusa.com/blog/what-happens-mortgage-closing-florida",
  },
  {
    title: "VA Loan Assumability Guide for Florida: Everything You Need to Know in 2026",
    description: "Can you assume a VA loan in Florida? Learn who qualifies, how the process works, benefits and risks, and when VA assumption makes sense in Orlando.",
    date: "March 12, 2026",
    category: "VA loans",
    url: "https://drmortgageusa.com/blog/va-loan-assumability-guide-florida-2026",
  },
  {
    title: "How to Qualify for a Mortgage with 1099 Income in Florida",
    description: "Self-employed or 1099 contractor in Florida? Learn how lenders calculate your income, what documents you need, and which loan programs work best in Orlando.",
    date: "March 10, 2026",
    category: "Self-employed",
    url: "https://drmortgageusa.com/blog/how-to-qualify-mortgage-1099-income-florida",
  },
  {
    title: "HELOC vs Home Equity Loan Florida: Which Is Better in 2026?",
    description: "HELOC or home equity loan in Florida? Compare rates, fees, tax benefits, and payment structures. Learn which option works better for your situation in Orlando.",
    date: "March 9, 2026",
    category: "Homeownership",
    url: "https://drmortgageusa.com/blog/heloc-vs-home-equity-loan-florida-2026",
  },
  {
    title: "How Seller Concessions Work in Florida (2026 Guide)",
    description: "Seller concessions let the seller pay your closing costs in Florida. Learn the limits for VA, FHA, and conventional loans, how to negotiate them, and when they make sense.",
    date: "March 3, 2026",
    category: "VA loans",
    url: "https://drmortgageusa.com/blog/how-seller-concessions-work-florida",
  },
  {
    title: "VA Loan Credit Score Requirements in Florida (2026)",
    description: "What credit score do you need for a VA loan in Florida? The VA has no minimum, but lenders do. Learn the real numbers, how overlays work, and how to qualify in 2026.",
    date: "March 3, 2026",
    category: "VA loans",
    url: "https://drmortgageusa.com/blog/va-loan-credit-score-requirements-florida-2026",
  },
  {
    title: "Down Payment Assistance Programs in Florida (2026)",
    description: "Complete guide to Florida down payment assistance programs in 2026. Hometown Heroes, FL Assist, FL HLP, Orange County DPA, and Osceola County programs. Orlando area focus. Up to $50K available.",
    date: "February 26, 2026",
    category: "Buying",
    url: "https://drmortgageusa.com/blog/down-payment-assistance-programs-florida-2026",
  },
  {
    title: "How to Read a Loan Estimate in Florida",
    description: "A clear, line-by-line guide to reading your Loan Estimate in Florida. Understand interest rates, closing costs, APR, and what to compare between lenders.",
    date: "February 22, 2026",
    category: "Buying",
    url: "https://drmortgageusa.com/blog/how-to-read-loan-estimate-florida",
  },
  {
    title: "IRRRL: VA Streamline Refinance Guide for Florida Veterans 2026",
    description: "Complete guide to the VA IRRRL (Interest Rate Reduction Refinance Loan) for Florida veterans in 2026. Requirements, costs, timeline, and when it makes sense to refinance.",
    date: "February 22, 2026",
    category: "VA loans",
    url: "https://drmortgageusa.com/blog/irrrl-va-streamline-refinance-florida-2026",
  },
  {
    title: "Orlando Housing Market Outlook 2026: What Buyers and Sellers Need to Know",
    description: "An in-depth look at the Orlando housing market in 2026. Home prices, inventory trends, interest rates, and what buyers and sellers should expect this year.",
    date: "February 22, 2026",
    category: "Market strategy",
    url: "https://drmortgageusa.com/blog/orlando-housing-market-outlook-2026",
  },
  {
    title: "VA Loan After Bankruptcy or Foreclosure in Florida",
    description: "Learn how Florida veterans can qualify for a VA loan after bankruptcy or foreclosure. Waiting periods, credit requirements, and steps to get approved explained.",
    date: "February 22, 2026",
    category: "VA loans",
    url: "https://drmortgageusa.com/blog/va-loan-after-bankruptcy-foreclosure-florida",
  },
  {
    title: "VA Loan for Surviving Spouses in Florida: Eligibility and Benefits",
    description: "Surviving spouses of veterans may qualify for VA home loan benefits in Florida. Learn who is eligible, what benefits apply, and how to apply for a Certificate of Eligibility.",
    date: "February 22, 2026",
    category: "VA loans",
    url: "https://drmortgageusa.com/blog/va-loan-surviving-spouses-florida",
  },
  {
    title: "How to Buy a Home in Orlando With No Down Payment in 2026",
    description: "You don",
    date: "February 21, 2026",
    category: "Buying",
    url: "https://drmortgageusa.com/blog/buy-home-orlando-no-down-payment-2026",
  },
  {
    title: "Can You Use a VA Loan More Than Once in Florida?",
    description: "Yes, you can use your VA loan benefit more than once. Learn how VA entitlement works, how to restore it, and how to use it again to buy a home in Florida.",
    date: "February 21, 2026",
    category: "VA loans",
    url: "https://drmortgageusa.com/blog/va-loan-entitlement-more-than-once-florida",
  },
  {
    title: "VA Loan vs Conventional Loan in Orlando: Which Is Better in 2026?",
    description: "Comparing VA loans and conventional loans for Orlando homebuyers in 2026. See which program saves more money based on your situation and eligibility.",
    date: "February 21, 2026",
    category: "VA loans",
    url: "https://drmortgageusa.com/blog/va-loan-vs-conventional-orlando-2026",
  },
  {
    title: "FHA vs. Conventional Loan in Florida: Which One Is Right for You?",
    description: "Compare FHA and conventional loans side by side. Learn the differences in down payment, credit score requirements, mortgage insurance, and which is better for Florida homebuyers.",
    date: "February 13, 2026",
    category: "Buying",
    url: "https://drmortgageusa.com/blog/fha-vs-conventional-loan-florida",
  },
  {
    title: "First-Time Homebuyer Guide: How to Buy Your First Home in Florida (2026)",
    description: "Step-by-step guide for first-time homebuyers in Florida. Learn about down payment assistance, loan options, credit requirements, and how to navigate the process.",
    date: "February 13, 2026",
    category: "Buying",
    url: "https://drmortgageusa.com/blog/first-time-homebuyer-florida-2026",
  },
  {
    title: "VA Loan Guide for Florida Veterans: Everything You Need to Know in 2026",
    description: "Complete guide to VA loans in Florida. Learn about 0% down payment, no PMI, eligibility requirements, and how to use your VA benefits to buy a home.",
    date: "February 13, 2026",
    category: "VA loans",
    url: "https://drmortgageusa.com/blog/va-loan-guide-florida-veterans-2026",
  },
];
